export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_CONFIRM_EMAIL_SUCCESS = 'USER_CONFIRM_EMAIL_SUCCESS';
export const USER_CONFIRM_EMAIL_FAIL = 'USER_CONFIRM_EMAIL_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAIL = 'RESET_PASSWORD_REQUEST_FAIL';

export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAIL = 'TRANSACTION_CREATE_FAIL';
export const TRANSACTION_UPDATE_SUCCESS = 'TRANSACTION_UPDATE_SUCCESS';
export const TRANSACTION_UPDATE_FAIL = 'TRANSACTION_UPDATE_FAIL';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';

export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

export const CALENDAR_EVENT_CREATE_SUCCESS = 'CALENDAR_EVENT_CREATE_SUCCESS';
export const CALENDAR_EVENT_CREATE_FAIL = 'CALENDAR_EVENT_CREATE_FAIL';

export const GET_CALENDAR_EVENTS_SUCCESS = 'GET_CALENDAR_EVENTS_SUCCESS';
export const GET_CALENDAR_EVENTS_FAIL = 'GET_CALENDAR_EVENTS_FAIL';
export const CALENDAR_EVENT_UPDATE_SUCCESS = 'CALENDAR_EVENT_UPDATE_SUCCESS';
export const CALENDAR_EVENT_UPDATE_FAIL = 'CALENDAR_EVENT_UPDATE_FAIL';
export const DELETE_CALENDAR_EVENT_SUCCESS = 'DELETE_CALENDAR_EVENT_SUCCESS';
export const DELETE_CALENDAR_EVENT_FAIL = 'DELETE_CALENDAR_EVENT_FAIL';

export const FLASHCARD_CREATE_SUCCESS = 'FLASHCARD_CREATE_SUCCESS';
export const FLASHCARD_CREATE_FAIL = 'FLASHCARD_CREATE_FAIL';

export const GET_FLASHCARDS_SUCCESS = 'GET_FLASHCARDS_SUCCESS';
export const GET_FLASHCARDS_FAIL = 'GET_FLASHCARDS_FAIL';
export const DELETE_FLASHCARD_SUCCESS = 'DELETE_FLASHCARD_SUCCESS';
export const DELETE_FLASHCARD_FAIL = 'DELETE_FLASHCARD_FAIL';

export const FLASHCARD_UPDATE_SUCCESS = 'FLASHCARD_UPDATE_SUCCESS';
export const FLASHCARD_UPDATE_FAIL = 'FLASHCARD_UPDATE_FAIL';

export const NOTES_SAVED_SUCCESS = 'NOTES_SAVED_SUCCESS';
export const NOTES_SAVED_FAIL = 'NOTES_SAVED_FAIL';

export const GET_LESSON_DATA_SUCCESS = 'GET_LESSON_DATA_SUCCESS';
export const GET_LESSON_DATA_FAIL = 'GET_LESSON_DATA_FAIL';

export const PAGES_SAVED_SUCCESS = 'PAGES_SAVED_SUCCESS';
export const PAGES_SAVED_FAIL = 'PAGES_SAVED_FAIL';
